### ISSUE TITLE
Prevent deletion of Publications that also exist in the Deposition app

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#100]
As a curator, the Curation app allows me to delete a publication. However, since the introduction of the Deposition app and the sync process that maintains publications in both the Curation app database and the Deposition app database a publication should not be able to be deleted from the Curation app database if it exists as a Publication in the Deposition app database (a publication object, not just a PMID string for a Body of Work).

**Comment by tudorgroza** [comment]
@twhetzel - I've done the curation side of things for this ticket, but can't find the 'Delete publication' functionality in the Curation App. I'm sure I'm looking in the wrong place. Can you please point me to where exactly can this be done? Thank you.

**Comment by tudorgroza** [comment]
@earlEBI @eks-ebi - thank you for helping me find the button.
In terms of expectation for the functionality mentioned in this ticket - would it be enough to add the submissions / body of works possibly associated with the publication to be deleted to that screen that is shown as a warning to confirm the deletion?

The one that starts with `Warning! All study details and ancestry information will be deleted` ...

**Comment by eks-ebi** [comment]
That sounds reasonable to me

**Comment by earlEBI** [comment]
I think the warning should be enough to stop us from deleting when a submission exists. But I don't see a problem with deactivating the delete button in this case either.

**Comment by ala-ebi** [comment]
The title talks about Publications but I think it's about Studies.
There is a bit of work by done for the issue that is not yet merged and it also revolves around Studies.
Some Studies that are not in ‘Publish Study’ status cannot be deleted, talked with Elliot and he agreed that this is weird.

**Comment by ljwh2** [comment]
1. @ala-ebi @eks-ebi I think this feature was implemented to prevent curators deleting studies that have a submission associated with them. When an author submits data, they recieve GCSTs, so we should never delete those GCSTs from the db. So that is already prevented. 

2. I think the original ticket refers to the scenario where a submission has been created, but the data has not been imported to curation yet. - see screenshot below. This publication should not be deleted, because there's a submission for it. However, once the submission is imported, we *do* want to allow deletion of the original study(s) (as in 1. above). 


![Screenshot 2021-02-22 at 12 32 18](https://user-images.githubusercontent.com/30795297/108709226-51f3ff80-750a-11eb-8649-c9709b13d70c.png)

**Comment by ljwh2** [comment]
@ala-ebi I tested the version in Snoopy hiding the button, and I think curators do need to have the flexibility to delete studies in certain cases, so it would be better to stick with the warning message. However, is it possible to make it more prominent? Highlighting the row with "Number of submissions in the deposition app" in a different colour could be enough.
