### ISSUE TITLE
In the tables for unpubublished data, does the study_tag need to be unique for all rows?

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#105]
In the tables for unpublished data, e.g. UNPUBLISHED_STUDY and UNPUBLISHED_ANCESTRY, do the values for `STUDY_TAG` need to be unique in the table? In the submission form, my understanding is that the `study_tag` value needs to be unique in the submission form. Does this unique constraint also need to be added for these database tables? How does the code handle loading "unpublished data" with respect to using the `study_tag` as a key for the data?

**Comment by tudorgroza** [comment]
The only constraint imposed by both `UNPUBLISHED_STUDY` and `UNPUBLISHED_ANCESTRY` on the `STUDY_TAG` field is `Non-NULL`. On import, the code checks for duplicates in the DB using the GCST - which makes sense, since if it's a Publication submission, the GCSTs exist by default and if it's a BoW submission, GCSTs are minted by the Deposition App.

/cc @twhetzel

**Comment by twhetzel** [comment]
Looks like the methods `syncUnpublishedStudies`, `getSamples`, and `addSummaryStatsData` use the study tag within the context of a submission or a publication so seems ok that the study tag does not have a unique constraint.

Closing
