### ISSUE TITLE
Some old submissions without metadata .yaml files

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1083]
As I understand, all summary statistics with a filename beginning GCST should have an accompanying .yaml metadata file. However some do not 
e.g. 
http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90012001-GCST90013000/GCST90012180/
http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90006001-GCST90007000/GCST90006934/
http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90011001-GCST90012000/GCST90011817/
http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90011001-GCST90012000/GCST90011857/

@earlEBI please could you look at these files and see if there is any obvious reason why the yaml file has not been generated, or common factor between them?

**Comment by earlEBI** [comment]
The only thing I can see that connects these studies is permissions of the files being set to -rw-r--r-- (as opposed to -rw-rw-r-- as newer files should be.)
I am able to create a yaml file for those affected when I am spotbot, but not as myself (permission is denied). 
I think there are quite a large number of files affected by this and I'm not sure how I could find all of them to fix.

**Comment by earlEBI** [comment]
On a separate / related issue... I'd like to know how the 'is_harmonised' field is set? When I try to manually create a yaml file for eg. GCST90012180 (which I did), is_harmonised is set to false... but there is a harmonised folder there: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90012001-GCST90013000/GCST90012180/
The same happened for multiple I tried. Is that how it should be?

**Comment by ljwh2** [comment]
I think James generated all the yaml files together and copied them to the directories. So could be that he has them somewhere. Otherwise, we need a solution to identify which eligible files are lacking yamls and create them in bulk.

**Comment by sprintell** [comment]
From James:

It’s been a manual process to identify these backlog of files missing their associated yaml. The way I identified and created them, was to go through each bin (of a thousand) in /nfs/production/parkinso/spot/gwas/prod/data/summary_statistics/ and run this

`for g in GCST*; do if [ ! -f $g/$g*-meta.yaml ] ; then  f=$(find $g -type f ! -name "*NR*" -name "$g*"); if [ -f $f ]; then gwas-ssf format $f -m -e --file_type=pre-GWAS-SSF; fi; fi; done`

So I would run this from /nfs/production/parkinso/spot/gwas/prod/data/summary_statistics/GCST90011001-GCST90012000 and then from the next bin of a thousand. This finds files missing the yaml that are named according to the GCST<ID>_<build> convention and creates the yaml file for them. I may have accidentally missed a directory of files, I’m not 100% sure. In order to run this you need to have gwas-sumstats-tools installed and have spot group permissions. 


Note that we set the file_type property for the file here because there is no way for it to know anything about the filetype. pre-GWAS-SSF is a safe bet as GWAS-SSF should have been done already but you may have to identify any non-GWAS-SSF files that haven’t already been annotated. I’d recommend trying this out on a single file or some test files if you’re not super comfortable running bash on the cluster.

**Comment by ljwh2** [comment]
@earlEBI all those first ones look like they are from the same submission, could you please check? 

Let's discuss the others.

**Comment by earlEBI** [comment]
Yes, one submission. 
All these GCSTs cover 4 submissions total.
