### ISSUE TITLE
Ensembl Mapping Errors During Full db remap

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#1157]

**Comment by ljwh2** [comment]
@sajo-ebi could you please add the list of errors here?

**Comment by sajo-ebi** [comment]
[Mapping_Ensembl_Error_List.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3NYQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f3379fee41a4d797e98fdaa4a0caa15dea1ac2b/Mapping_Ensembl_Error_List.xlsx)

Attached is the file containing variants which are getting errors from Ensembl & also if the mapping was successful with last release Dec 2021

**Comment by ljwh2** [comment]
Response from Ensembl: Thank you for following up on this. It looks like you are receiving the error
due to some changes we made to sequence region names in Ensembl Release 110.
We will fix the issue for Ensembl Release 111, which is expected to be
published in November. In the meantime, I'm afraid you will need to use
Ensembl Release 109 for your analyses. I hope that this helps!

**Comment by ljwh2** [comment]
https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/gwas-data-services/10
