### ISSUE TITLE
Sumstats not available on FTP after removing embargo (Submission id: 64ed45b2788f0000010f1043)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1172]
I removed the embargo for this submission on 13th Oct, and it is still not available on FTP. 

GCST90281041 and GCST90281042

**Comment by sajo-ebi** [comment]
@Santhi1901 this was due to an old bug [https://github.com/EBISPOT/gwasdepo-deposition-service/issues/161](https://github.com/EBISPOT/gwasdepo-deposition-service/issues/161) the sumstats were not copied to staging folder , have manually triggered process to copy , it should be release after sumstats ftp script runs overnight

**Comment by sprintell** [comment]
Hi @Santhi1901 could you pls confirm this is done ?

**Comment by sprintell** [comment]
Hi @Santhi1901 could you pls confirm this is done ?

**Comment by Santhi1901** [comment]
yes these GCSTs are available on FTP
