### ISSUE TITLE
LSF to Slurm Migration for Bamboo Pipelines and Codon Cron Scripts

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#1180]
- [ ] Bamboo Pipelines Script Migration
- [ ] Codon- Script Migration

https://docs.google.com/spreadsheets/d/1sS7rhjVe3hlbR3FI91xfmJBHdDuepCTg1KgvjbSVtpQ/edit#gid=0

**Comment by sajo-ebi** [comment]
Have made changes to the Codon cron scripts & Mapping pipeline code to make them run using Sbatch & Scrontab , encountered error in executing command line script option with SLurm as it was accepting arguments to the script , discussed with Slurm team & got suggestion to change to Sbatch scripts instead of command line whenever arguments are passed to the script , need to do this for Bamboo Data release scripts , hence this ticket needs bit of more work but shouln't take huge time

**Comment by sajo-ebi** [comment]
Bamboo Data releases jobs have been rewritten as Sbatch scripts but we are getting error with wall time limit w.r.t SLurm cluster need to increase  wall limit & then rerun the Data release next time
