### ISSUE TITLE
Submission Interface template validation - Country of Recruitment and Array Manufacturer

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#128]
### **Country of recruitment**
Countries listed in the 'country of recruitment' column on the 'Sample' tab of the submission template pass validation, even if they don't match the accepted list given here: https://www.ebi.ac.uk/gwas/docs/countries . 

For example, UK was given instead of U.K., and USA instead of U.S., resulting in no CoR being imported to the curation interface. 

Non-matching countries need to fail validation. 

### **Array manufacturer**
Array manufacturer values on the 'study' tab of the template also need to fail validation if they do not match one of the three accepted manufacturers.

**Comment by tudorgroza** [comment]
@earlEBI - some remarks on the 2 issues above:
 * **Country of recruitment** - while the field is mandatory, there is no list of expected values provided in the template - and hence no value-driven validation is performed. In order to make this happen, we would have to include the list of all countries in the METADATA schema. Please note that matching for validation is done on exact values - and hence if the user specifies UK and the country in the list is U.K. - this will lead to a failure (if we introduce the country list). Should we introduce the mandatory country list?
 * **Array manufacturer** - the field / column is **not** mandatory in the schema - hence no validation is performed. I can probably adapt the validator continue having the column relaxed (given it's non-mandatory status), however if a value is provided to enforce validation. Is this the desired process / outcome?

/cc @jdhayhurst @twhetzel

**Comment by earlEBI** [comment]
- country of recruitment - I think yes. 
- Array manufacturer - can you limit the character number to ~10, maybe? 
@ljwh2

**Comment by tudorgroza** [comment]
@earlEBI - unfortunately, I can't. @jdhayhurst has introduced a 255 chars limit across all cells - but it's not something we can actually enforce. How does the character limit help with the validation? Would we encounter the same issue?

**Comment by tudorgroza** [comment]
@earlEBI - Closing this ticket. I've created 2 corresponding tickets in the appropriate repos:
* https://github.com/EBISPOT/gwas-template-services/issues/58
* https://github.com/EBISPOT/gwasdepo-template-validator/issues/2
