### ISSUE TITLE
Investigate & plan options for GWAS Diagram

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1322]
Some notes are here:
https://docs.google.com/document/d/1tUkwMz0ZfPFC_Dw4PVh12HV3sn43xHyhlzbQJej0lro/edit?usp=sharing

Analyse possibility to display pre-generated filtered diagrams

**Comment by ala-ebi** [comment]
Diagram file wasnt being generated in garfield because there is a logic that says if there is a file with a certain name used for caching, then we dont need to generate a new diagram… We needed to rename that file (to back it up) before triggering the diagram regeneration so that the cache file is not found.

**Comment by ala-ebi** [comment]
Virtuoso giving HTTP 500 internal server error. A restart appears to have fixed it

**Comment by ala-ebi** [comment]
Pussycat giving error
```
[http-nio-10180-exec-111] o.s.boot.web.support.ErrorPageFilter     : Forwarding to error page from request [/gwasdiagram/associations] due to exception [GC overhead limit exceeded]
java.lang.OutOfMemoryError: GC overhead limit exceeded
```
will increase the memory for Tomcat and try again
