### ISSUE TITLE
Structured ancestry missing for the study GCST90320056 after importing to the curation app

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1326]
The structured ancestry for this study is missing after importing to the curation app, but the detailed sample description is still present. 

This is a user submission and the ancestry looks all good in the template. https://www.ebi.ac.uk/gwas/depo-curation/submissions/65ef0c7ab73c7400017bb326

**Comment by ljwh2** [comment]
Please prioritise this @sajo-ebi

**Comment by sajo-ebi** [comment]
@Santhi1901 the issue is due to type in Sample Tab , the study tag for 'GCST90320056' is 'Multi_pRCC_meta' but in Sample sheet it is provided as 'Multi_pRCC_Meta' (m is captital in Meta). the code in Curation app is case sensitive for comparing study tags , hence the structural ancestry is not inserted . Please upload the template again by correcting the Typo in Sample sheet

**Comment by Santhi1901** [comment]
The study tag was corrected, and the structured ancestry was imported correctly.

**Comment by sprintell** [comment]
@sajo-ebi 

Please create a ticket to ignore case sensitivity during import
