### ISSUE TITLE
Replace obsolete EFO terms

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1328]
From the 'Update and obsolete EFO job report' e-mail on 17 May 2024, 20 terms were obsolete. 

I have deleted some which were not in use in the Catalog, and created a ticket to delete another three. 

The remainder need replacing. Here is a table listing the obsolete EFOs and their replacements. 
Please update via the backend. 

[Obsolete EFO replacements.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2Y3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5c020eece92e5aa105464ceaa59b494879fa11c/Obsolete%20EFO%20replacements.txt)
 

(note, some studies will have more than one EFO attached. Only the obsolete EFO should be overwritten.)

**Comment by ala-ebi** [comment]
all of the terms have a wrong/empty "term_replaced_by" field in OLS API which the Obsoletion App uses to know the replacement term.

The following EFO terms have "term replaced by" instead of "term_replaced_by":
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=EFO_0004624
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=EFO_0005192
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=EFO_0008170
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=EFO_0010594
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=EFO_0021572
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=EFO_0800624
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=EFO_0802653
The following MONDO terms have null in "term_replaced_by":
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=MONDO_0011876
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=MONDO_0015335
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=MONDO_0017428
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=MONDO_0017760
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=MONDO_0041161

Will be letting EFO team know to avoid this happening in the future

**Comment by ljwh2** [comment]
@ala-ebi to double check with Lizzy and replace the mondo terms in the database

**Comment by ala-ebi** [comment]
done

**Comment by ljwh2** [comment]
@ala-ebi just flagging that the null MONDO terms are still mentioned in the Update and obsolete EFO job report for current DR

**Comment by earlEBI** [comment]
re: MONDO_0041161, HP_0040298 has now been imported to EFO. https://github.com/EBISPOT/efo/issues/2226#issuecomment-2275389551

Also, please see this ticke for any action required: https://github.com/EBISPOT/efo/issues/2227#issuecomment-2275479509

**Comment by sprintell** [comment]
Delete obsolete terms

**Comment by ala-ebi** [comment]
EFO: updated and deleted obsolete EFO terms and studies in mongo and oracle.
MONDO: updated mongo studies to use the new EFOs, no oracle changes needed

**Comment by ala-ebi** [comment]
EFO: updated and deleted obsolete EFO terms and studies in mongo and oracle.
MONDO: updated mongo studies to use the new EFOs, oracle updates need to be done after trait sync runs (hasnt happen as codon maintenance ongoing)

**Comment by sajo-ebi** [comment]
this is blocked by [1421](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1421)
