### ISSUE TITLE
GWAS Summary Stats FTP Release Bamboo plan should fail when files are not moved 

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#136]
For the "GWAS Summary Stats FTP Release" Bamboo plan, when log messages show that files have not been moved the Bamboo plan still indicates that it ran successfully. This is misleading because it appears files that should be staged for release are not being added.

Log message from plan:
`mv: cannot move `MY_DIR/gwas/summary_statistics/GCST008311' to `MY_DIR/gwas/summary_statistics/KimW_31000673_GCST008311/GCST008311': Directory not empty`

**Comment by jdhayhurst** [comment]
This should actually never happen and is happening because of the bug described here (studies existing in both unpublished and published states): https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/gwas-utils/30

If we make the script exit at the point mentioned, the other files cannot be released either. So I would prefer to keep it as a log that we can intervene on rather than an out right failure.

**Comment by jdhayhurst** [comment]
email the logs so we pick them up

**Comment by jdhayhurst** [comment]
was not able to find a way to make bamboo do something like a MAILTO with the stderr, nor was I able to mail the stderr AND have it logged with bamboo in any neat way. However, exceptions are picked up and if any are found they are appended to the email report. The above was not considered an exception, and for this reason and portability, I changed the subprocess (mv) to a shutil move.
