### ISSUE TITLE
Yaml files needs to be updated for the PMID:38448586 (submission ID: 6564aefc53c4ef0001094614)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#1379]
The traits in the UI are correct, but the yaml files still have old traits and need to be updated. 

Total 233 studies.

**Comment by karatugo** [comment]
Accession IDs: 90301941--90302173

**Comment by eks-ebi** [comment]
@eks-ebi to test this once completed (Santhi will be on leave next week)

**Comment by karatugo** [comment]
Looks good except for this one: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90301001-GCST90302000/GCST90301942/

**Comment by karatugo** [comment]
There was something wrong with the one above due to caching I believe. Now all looks good to me.

**Comment by ljwh2** [comment]
@eks-ebi to verify

**Comment by eks-ebi** [comment]
@karatugo Thanks I can confirm that the trait is now correct in the YAML for this study: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90301001-GCST90302000/GCST90301942/

**Comment by eks-ebi** [comment]
@Santhi1901 there is one problem remaining in the traits in the UI, which was spotted by user Martijn Zoodsma on gwas-info. I've looked into it and I'm pretty sure that there is just one study with an incorrect Reported trait and EFOs:

`GCST90301976` currently has Reported trait `Cholesteryl esters to total lipids ratio in IDL`, should be `Total cholesterol to total lipids ratio in IDL`. And the EFOs are currently `cholesteryl esters:total lipids ratio` and `intermediate density lipoprotein measurement`, should be `cholesterol:total lipids ratio` and `intermediate density lipoprotein measurement`.

I haven't made the change myself because I'm not 100% sure that I understand how you did the reannotation, and I could have made a mistake. Could you please have a look when you get back and make sure this is the correct way to fix the issue?

**Comment by Santhi1901** [comment]
corrected the trait+EFO for GCST90301976 and republished

**Comment by sprintell** [comment]
Hi @Santhi1901 could you please confirm if this ticket can be closed ? Thanks

**Comment by Santhi1901** [comment]
it can be closed
