### ISSUE TITLE
Deleted obsolete EFO from depocuration

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#1454]
EFO term http://purl.obolibrary.org/obo/HP_0002355 is obsolete and is no longer linked to any studies, however I am unable to delete it from depocuration.

Can it be deleted from the back end?

**Comment by ala-ebi** [comment]
the trait was linked to a study that doesnt appear in the studies table because it doesnt have submissionId. These studies without submissionId are for versioning purposes, to avoid this issue from happening in the future we could instead of deleting obsolete EFOs, just mark them as Obsolete (new db col), or we can drop the EFO from versioning, or we can add a filter in the studies table to show these kind of studies without submissionId so that curators are able to delete them manually
