### ISSUE TITLE
Authors appearing in wrong order

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1459]
A user reported that publication authors are appearing in the wrong order in GWAS catalog UI than in the original record in EuropePMC, for example:

https://www.ebi.ac.uk/gwas/publications/39271666
https://europepmc.org/article/MED/39271666

This may be happening on import to curation db.

Note, there is functionality in the old curation app to rearrange the order of authors, this is unused and not required in Depo-Curation. The order of authors with respect to EuropePMC must be maintained on data release.

**Comment by Santhi1901** [comment]
pmid:38062574 also shows an incorrect author order in the curation app; it was not added in depo-curation. It was added in curation app in Dec 2023

**Comment by sajo-ebi** [comment]
@ljwh2 discussed with @eks-ebi in sprint planning today for the Pmids since this feature was not implemented in Depo Curation we will need to manually update DB in curation DB for the Pmids which are impacted & we can implement changes in Depo Curation to allow sorting of authors to avoid issues for future EuropeMC import

**Comment by sajo-ebi** [comment]
the permanent fix has been release to production & the authors for the mentioned Pmid have also been sorted in DB
