### ISSUE TITLE
"Unpublished" tables are re-populated after manually deleting data

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/goci#149]
There have been cases where submissions originally submitted as a Body of Work (ie prepub/unpublished) and then receive a PMID and are moved to the "published" tables in the database are not removed from the "unpublished" tables.  In order to resolve this for the Data Release, the data in the tables: `UNPUBLISHED_STUDY`, `UNPUBLISHED_ANCESTRY`, and `UNPUBLISHED_STUDY_TO_WORK` was deleted manually and the data release started. This did fix the issue for the data release.

However, checking the curation database the following day after manually deleting data from the "unpublished" data, the data was added back to the `UNPUBLISHED_STUDY` and `UNPUBLISHED_ANCESTRY` tables. I'm not sure if this is an issue with the Deposition sync or that the row from the `BODY_OF_WORK` table should also have been removed or some other database change was needed. 

The effected publications are: (Hillary[PMID:32641083], Ellinghaus[PMID:32558485], Gabryszewski[PMID:32650023])

**Comment by tudorgroza** [comment]
@twhetzel - had a look at those 3 publications / submissions and I can confirm that they are being brought back because of their incorrect status in the Deposition App.

The sync "rule" is: submission.status == `SUBMITTED` and submission.provenanceType == `BODY_OF_WORK` ... and then some other stuff related to embargo date, which is irrelevant in this discussion.

Once brought in - they stay there until the associated publication is found and the submission is imported. During the import process (in one of the many steps) the Curation App calls the Deposition App and sets submission.status to `CURATION_COMPLETE`.

In the case of the 3 submissions above - given that they all had import issues, this particular step was most likely not performed. I've updated them in the DB - so next time they shouldn't reappear.

**Comment by twhetzel** [comment]
Perfect! I will remove them again from SPOTPRO and we can check tomorrow.

**Comment by twhetzel** [comment]
The unpublished data was manually deleted.
