### ISSUE TITLE
Splitting out background EFOs in database

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#164]

**Comment by ljwh2** [comment]
in roadmap for April

**Comment by ljwh2** [comment]
@eks-ebi Elliot has the full list of studies and traits that require splitting

**Comment by ljwh2** [comment]
https://docs.google.com/document/d/1agaBcPxuCws0pKnuZh_PJylk5TO84FG9YGgpxIXzZpY/edit?usp=sharing

**Comment by eks-ebi** [comment]
Testing 2021-06-14:

- Background traits have now been moved to a separate field. I checked several random studies and **all had the background trait correctly split**.
- I would like to do a comprehensive check for any that might have been missed (e.g. due to mismatches in EFO labels, curation changes since background traits were review etc.) - @ala-ebi can I get a full Catalog studies spreadsheet based on this data to cross-reference against the original list of traits that needed to be split?

**Comment by ala-ebi** [comment]
[all catalogue study traits.xlsx](https://github.com/EBISPOT/goci/files/6649758/all.catalogue.study.traits.xlsx)
@eks-ebi This file contains the concerned fields, there's too many rows in the sheet so if you have a criteria you wish to filter by let me know.

**Comment by eks-ebi** [comment]
Did comprehensive check of the excel file today:

In summary:

1. all background traits seem to have been correctly moved to the new BGEFO field 
2. for 2 studies, it looks like the main trait was incorrectly moved to the BGEFO field as well:
**GCST010089**
Reported: "Sudden cardiac arrest in coronary artery disease"
MAINEFO: `NA` [should be `sudden cardiac arrest`]
BGEFO: `coronary artery disease | sudden cardiac arrest` [should be `coronary artery disease` only]
**GCST009983**
Reported: "Trauma exposure in major depressive disorder"
MAINEFO: `NA` [should be `trauma exposure measurement`]
BGEFO: `trauma exposure measurement | unipolar depression` [should be `unipolar depression` only]
