### ISSUE TITLE
Prefilled templates do not pass validation due to character limit

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#202]
Prefilled templates for sumstats-only submissions now fail validation, due to character limit. We need a solution to allow upload of such templates. In the example attached, the column which exceeds the character limit is "Discovery sample". Note that this data does not exist in the metadata submission template. There is a column called "Sample description" in the metadata template, but this not the same information. The "Discovery sample" field in the database is generated in the curation app either as a combination of sample number (individuals/cases/controls) and ancestry, or entered directly as free text.[https://app.zenhub.com/files/2995118/6acf667b-7a47-4aa0-9d02-91501dbeb8fb/download](https://app.zenhub.com/files/2995118/6acf667b-7a47-4aa0-9d02-91501dbeb8fb/download)

**Comment by tudorgroza** [comment]
@ljwh2 @jdhayhurst - I had a look into this and the 'Discovery sample' column in the `SUMMARY_STATS` template (since this is not a `METADATA` template corresponds to the `sample_description` field in the schema that does enforce the 255 field size.

In the template service, this column is only introduced for summary stats submissions. In the Curation App, the import of summary stats submissions does not use this data.

Resolution: I will remove the 255 characters constraint and this should fix things.
