### ISSUE TITLE
Do gap analysis of status of metadata for PUBLISHED and PUBLISHED_WITH_SS publications

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/goci#216]

**Comment by tudorgroza** [comment]
@ljwh2 - this is related to #230 

Outcome:
 * 131 NOT published & NOT pValue & NO GCSTs => ELIGIBLE
 * 4 NOT published & WITH pValue & NO GCSTs => ELIGIBLE
 * 259 NOT published & NOT pValue & NO GCSTs => PUBLISHED
 * 5 NOT published & WITH pValue & NO GCSTs => PUBLISHED
 * 15 NOT published & NOT pValue & WITH GCSTs => PUBLISHED
 * 2780 WITH published & NOT pValue & WITH GCSTs => PUBLISHED
 * 5 NOT published & NOT pValue & WITH GCSTs => PUBLISHED_WITH_SS
 * 2 NOT published & WITH pValue & WITH GCSTs => PUBLISHED_WITH_SS
 * 88 WITH published & NOT pValue & WITH GCSTs => PUBLISHED_WITH_SS
 * 286 WITH published & WITH pValue & WITH GCSTs => PUBLISHED_WITH_SS

[list.xlsx](https://github.com/EBISPOT/goci/files/5390179/list.xlsx)

Would be great to set up a meeting and discuss these.

**Comment by ljwh2** [comment]
@tudorgroza happy to do this monday morning

**Comment by tudorgroza** [comment]
Sounds good. Thank you.

**Comment by tudorgroza** [comment]
@eks-ebi @ljwh2 - I cleaned up the publications and we're in a pretty good state.
The latest fix in the sync that implements the algorithm described by Elliot in https://github.com/EBISPOT/goci/issues/230 fixed most of the issues mentioned above.

We're left with a couple of handfuls of publications that need to be synched across (the sync is now broken for some reason - I'm looking into it) and 2 problematic - see below.

I could have set the status according to the algorithm, but wanted to double check:
 * PMID 25823930 - 1 study (1440) with one GCST - Status `Unpublished from catalog`
   * This should be `ELIGIBLE` - correct?
 * PMID 21845381 - 1 study (1612) with one GCST - Status `Unpublished from catalog`
   * This should be `ELIGIBLE` as well - correct?

Thank you.

**Comment by ljwh2** [comment]
These are examples where the publication has been permanently unpublished from the Catalog (study was retracted) rather than temporarily unpublished for editing. These are qualitatively different things and really should have different statuses than the regular unpublished (Elliot and I discussed this scenario, not sure with Tudor or not). I don't know how much work it would be to create an additional status for these, or we just change them to Curation Abandoned. In theory they are different from Curation abandoned because they were previously available to users, and now are not. But I don't think users care too much about this.

**Comment by tudorgroza** [comment]
Would `Permanently unpublished from catalog` be a good status name? I can add it and set this status for the 2 publications. I can then remove them from the Depo DB.

**Comment by ljwh2** [comment]
Yes perfect. Just tagging @eks-ebi for sanity check

**Comment by eks-ebi** [comment]
Yes `Permanently unpublished from catalog` sounds like a perfect status for these cases

**Comment by tudorgroza** [comment]
Ok - I'll do the update. Thank you.
