### ISSUE TITLE
Investigate why publications that should be ELIGIBLE have status PUBLISHED

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/goci#230]

**Comment by tudorgroza** [comment]
@ljwh2 @eks-ebi - Can you please confirm the following for me:

* (`PUBLISHED_WITH_SS`) If a publication exists in the Curation App and has been `published` and has `pValueSet` - there is an expectation for that publication to have summary stats metadata present and an eventual submission created on it in the Deposition App should provide the user with the pre-filled template (aka SUMMARY_STATS submission).
* (`PUBLISHED`) If a publication exists in the Curation App and has been `published` but does *not* have `pValueSet` or (`ELIGIBLE`) If a publication exists in the Curation App and has *not* been `published, an eventual submission created on it in the Deposition App should provide the user with the full submission template (aka METADATA submission)

Thank you!

**Comment by eks-ebi** [comment]
@tudorgroza I'm looking at this now and I think a couple of things might be getting mixed up. Are you able to pull out a couple of examples of publications with each status (PUBLISHED_WITH_SS, PUBLISHED, ELIGIBLE) together with their submission status (CLOSED, OPEN FOR SUBMISSION, OPEN FOR SUMMARY STATISTICS SUBMISSION)? These were displayed together on the deposition interface in an early iteration, before we decided to hide the publication status because it was confusing users. I think seeing them side by side will jog my memory so I can give you a more clear answer.

**Comment by ljwh2** [comment]
As I understand it, @tudorgroza definitions of the different statuses are correct, but the outcomes are not:
(PUBLISHED_WITH_SS) - should be CLOSED FOR SUBMISSION 
(PUBLISHED) - should be SUMMARY_STATS submission (prefilled template)
(ELIGIBLE) - should be METADATA submission

**Comment by eks-ebi** [comment]
That's how I understand it too

**Comment by tudorgroza** [comment]
@ljwh2 - this is indeed the current status mapping.
However, I've now encountered at least 2 cases where it seems that this mapping is incorrect. Or more concretely, not that the mapping is incorrect ... but rather that the rules used to assign that publication status as sync time are wrong. I'm running in parallel an analysis on the deposition data to understand the current status of the publications ...

Let's take a step back ... there are three "types" of publications we want to expose:
1. Publications that have been curated - and are listed just so that the users can see them there - but they can't interact with them
2. Publications imported / added to the curation queue - but with no additional metadata / data present - for these we want to accept the full template from users
3. Publications imported and with GCSTs assigned - but still open for users to provide summary stats.

I need to understand the set of parameters that define all of the above.
 * For #2 ... the rule seems to be: `isPublished` set to `False` - are there any other?
 * For #1 and #3 ... things get messed up (at least based on the current assignment). What are the rules that define a publication open for summary stats submission? (aka #3) It has to have GCSTs assigned already ... but what are the rules - and what makes them different to those that are closed for submission? (aka #1)

**Comment by eks-ebi** [comment]
Agreed on the three types of publications.

This is what I think the parameters are for each:
1. `isPublished` = `True` _and_ has `pValueSet` (i.e. at least one study in the publication has summary statistics associated with it already) --> nothing further required from authors, so CLOSED
2. `isPublished` = `False` --> we are seeking both metadata and sumstats, so OPEN FOR SUBMISSION (full template)
3. `isPublished`= `True` _and_ doesn't have `pValueSet` (i.e. no studies in the publication have summary statistics yet) --> we have the metadata but we're seeking sumstats, so OPEN FOR SUMMARY STATISTICS SUBMISSION (pre-filled sumstats template)

**Comment by eks-ebi** [comment]
There is one weakness - we don't account for the possible situation where we already have sumstats for a subset of studies in a publication (making it CLOSED) but an author wants to contribute additional sumstats for the remaining studies. But I think we decided that would be a fairly rare occurrence and would wait to see if authors contacted us in those situations to see if it would be necessary to support in future. Don't think we've had any users ask about that scenario so far.

**Comment by eks-ebi** [comment]
@tudorgroza I've finally gone through the gap analysis etc. in more detail and have some more detailed specifications agreed with Laura this morning. Hopefully it's in line with the answers I gave you the other day, but a bit more complete:

[Publication status definitions.png](https://images.zenhubusercontent.com/5ebd0095cdca5a6323f696ae/6c313190-5c59-4f7e-abd6-fccc23b65eed)

Let me know if you want to talk through any details.

**Comment by tudorgroza** [comment]
Thank you @eks-ebi .
How do I know if a paper is a `Scientific pilot` or a `CNV paper`?

**Comment by eks-ebi** [comment]
An important thing to note is that all decisions should be based on the *current* state of the study, not the history of whether a change of state occurred
* e.g. isPublished should be defined by whether the study currently has the status "Publish in Catalog", not whether it has a published date - because if it was published and is now unpublished, that change needs to be reflection
* similarly, pValueSet=TRUE should mean that the p-value box is *currently* ticked, not that it was ticked at some point in the past (I think that's the cause of Aoife's recent issue)

This seems to have been a bit mixed up in the way it was originally set up, which seems to be causing a lot of the unexpected statuses in the deposition interface.

**Comment by eks-ebi** [comment]
> How do I know if a paper is a Scientific pilot or a CNV paper?

Those are study-level Curation statuses in the Curation interface (and therefore I assume also in the database?)

**Comment by tudorgroza** [comment]
Oooooh! Thank you! 💡

**Comment by tudorgroza** [comment]
@eks-ebi - challenging question: what do we do if you decide to 'Abandon curation' on a publication that has a submission started on it?

**Comment by eks-ebi** [comment]
@tudorgroza I've been thinking about your question but don't have a good answer yet. Might be good to get @ljwh2's opinion next week

**Comment by tudorgroza** [comment]
All good - hopefully these are edge cases :)

**Comment by ljwh2** [comment]
Papers typically become curation abandoned when they come in from the literature search as eligible, but on closer reading turn out to not be eligible eg because the number of variants is <100K or the GWAS data is previously published. However if valid sumstats data is submitted for such a paper it in some sense becomes eligible, or at least merits more discussion/review. Therefore it would be appropriate for the curator to be unable to change the status to curation abandoned if there is a submission in progress. Alternatively it would acceptable to the curator to recieve some kind of alert, not sure how that would be handled in deposition though. @eks-ebi @tudorgroza

**Comment by ljwh2** [comment]
Just making sure I've thought through the whole workflow from the curator side - so if the curator is unable to change the status, they would then review the submission and communicate with the submitter, if the submission turns out to be ineligible (unlikely if they have already submitted, but could be the case if they haven't passed validation yet) then we remove the submission and can then change status to curation abandoned

**Comment by ljwh2** [comment]
Does this make sense to you @eks-ebi ?

**Comment by eks-ebi** [comment]
Yes that makes sense, I think that sounds like a good workflow

**Comment by tudorgroza** [comment]
Ok - I need to think about how I'm going to handle the blocking of the status change, since it is first done in Curation and then sync'ed to Deposition ....

**Comment by ljwh2** [comment]
@tudorgroza I don't want this to be a drain, because i think it is going to be a very unusual case. I can't think what the consequences would be if the curator changed status to curation abandoned (under the proposed scheme) and there was still a submission in progress - I imagine bad consequences?!

**Comment by tudorgroza** [comment]
As it stands ... nothing happens. But I do need to find a way to notify the curation team of such an event.

**Comment by ljwh2** [comment]
So if there are no consequences for the deposition app, it doesn't necessarily need to be blocked, but the curator needs notification of some kind.

**Comment by tudorgroza** [comment]
Yep. I'll create a ticket to produce a daily depo sync report - to be emailed to gwas-dev. In this way we will have complete visibility.
