### ISSUE TITLE
Monitor prepublished submissions for publication in PubMed

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/goci#37]
To prevent duplicate publication being added into curation, we need to provide curators with feedback that a publication has previously been submitted without a PubMed ID by the author.
-Need to add status of submission publications to curation interface
-need to display match likeliness for publication prior to study creation
-need to add PubMed ID to publication in Deposition.

-changes needed to Curation and Deposition UI/backend.

**Comment by tudorgroza** [comment]
@jstewart-ebi - do you want to add this to the deposition backend? (as a 'suggestion' associated with the manuscript when created)

**Comment by jstewart-ebi** [comment]
I think so, I think curators and authors will need to be able to add a PubMed ID to a manuscript. I think we'll need to support it from Curation and Deposition. Do you want to make a specific endpoint for it, or PUT the updated submission publication?

**Comment by tudorgroza** [comment]
There's two things:

1. The finding / matching of manuscripts to pubmed publications, which will lead to a list of candidate PMIDs and some measure of similarity. This - is something I could do in the background when the manuscript is first created ... and then ... somehow have it displayed to the curators

2. Adding a PMID to a manuscript - this can be done in various ways and it really depends on the desired downstream impact. One option could be for me to transform the `manuscript` into a `publication` (since we now have the PMID). 	Alternatively, I can just have the PMID added to the manuscript.

Can we discuss this today in the iteration meeting?

**Comment by jstewart-ebi** [comment]
Released.
