### ISSUE TITLE
GOCI deployment migration to codon

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#480]
The deployment plans reference ebi-cli. Will need to change to codon and update file paths accordingly

**Comment by jdhayhurst** [comment]
http://gromit.ebi.ac.uk:10001/browse/GWAS-GFS/deployments

**Comment by jdhayhurst** [comment]
cloned existing deployment to http://gromit.ebi.ac.uk:10001/deploy/viewDeploymentProjectEnvironments.action?id=48103425

**Comment by jdhayhurst** [comment]
completed "Production Tools"

**Comment by sajo-ebi** [comment]
@jdhayhurst @sprintell have analysed the Goci Deployment Bamboo job , the job includes copying of war file to a directory in Hinxton & Codon doesn't have write access to Hinxton . The VM for curation 'ves-ebi-e4' is also in Hinxton , we will need to provision a new VM in Harlow in order to allow Codon write access.
`ssh ebi-cli "sudo -u spo_adm cp ${bamboo.spot_dir}/sw/${bamboo.env_dir}/gwas/interfaces/curation/gwas#deposition.war /nfs/www-prod/web_hx2/gwas/interfaces/deposition/gwas#deposition.war"`

**Comment by sprintell** [comment]
@sajo-ebi  please create a workflow diagram for this ...

**Comment by sajo-ebi** [comment]
Goci has been deployed successfully in Gwas-snoopy using Bamboo & on Dev2 branch , now pending items is for staging & Prod server
