### ISSUE TITLE
Locate missing sumstats files for 34873335 / 6130d5e6088ad000014c5e72

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#565]
This was a prepublication submission that has now had a PMID added and has been published in the curation interface.

Study landing pages are visible, but the sumstats links give a 403 error:
https://www.ebi.ac.uk/gwas/studies/GCST90027163
https://www.ebi.ac.uk/gwas/studies/GCST90027164

**Comment by jdhayhurst** [comment]
These were "unpublished" and then "published". The new method of handling this uses unix groups to manage access. The access was removed correctly but never reinstated. This is because the ftp sync code simply lists the dir contents so it has recognised that the access needs modifying. This method: https://github.com/EBISPOT/gwas-utils/blob/cbdbfac9540099e1ef4cc917811b90fc63e87c01/ftpSummaryStatsScript/ftp_sync.py#L54 needs updating.

**Comment by jdhayhurst** [comment]
fixed the code above, reran sync and the two affected studies were picked up

**Comment by eks-ebi** [comment]
Thanks @jdhayhurst ! I've checked the links and they are both working now.
