### ISSUE TITLE
Import button disabled for unpublished submission (PMID:33679876)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/goci#599]
3 studies:GCST90093118-GCST90093120 was unpublished to edit and uploaded the edited sheet through depo-curation app, but not able to import to curation app as the 'import' button is disabled. https://www.ebi.ac.uk/gwas/curation/submissions/61e84149911f5a0001f7d2c0.

**Comment by ala-ebi** [comment]
problem 1: publication was in ELIGIBLE status after the submission was done, causing the import button to be disabled, updated the publication to the UNDER_SUBMISSION status to resolve it
problem 2: after changing the publication status, the import hung because another big import was running that's locking the tables on oracle side, to resolve it we had to wait for the big import to finish and restart
