### ISSUE TITLE
missing mapped trait and EFO trait in tsv files for studies and associations

### ISSUE THREAD

**Issue by mcerezof** [EBISPOT/goci#613]
Both files "gwas_assoc.tsv" and "gwas_studies.tsv" (you can download them from https://www.ebi.ac.uk/gwas/docs/file-downloads) contain empty cells in the columns "mapped_trait" and "mapped_trait_uri". There are more empty cells for gwas-catalog-v.1.0.3-studies for older studies.

**Comment by ljwh2** [comment]
@eks-ebi Could you do some investigation to find out what might be going on here, with some specific examples please?

**Comment by eks-ebi** [comment]
Update:
- 73 unique EFO terms were missing from the download, across 130 studies (142 individual study-EFO combinations)
- @ala-ebi pulled out what was expected to be displayed for each trait from the database
- I cross-referenced that to Zoe's list of EFOs with the missing 'www' in the EFO URI, and that accounts for 46/73 terms - these should be fixed by EFO ticket EBISPOT/efo#1456
- 3 other terms have a typo in the EFO_URI as it appears in the GWAS Cat database: **EEFO**_0600044, **FO**_0600088, EFO_002007 (should be EFO_0020070) - I have corrected these in the curation database
- That leaves 24 terms still to resolve

**Comment by eks-ebi** [comment]
@ala-ebi @ljwh2 Here are the remaining missing terms with my analysis of the problem and proposed solutions. Let me know what you think:
[https://app.zenhub.com/files/2995118/90a67cfc-c0c2-4ea0-86cb-8bc33f0e6a3f/download](https://app.zenhub.com/files/2995118/90a67cfc-c0c2-4ea0-86cb-8bc33f0e6a3f/download)

**Comment by eks-ebi** [comment]
Issues now resolved for all but one of the terms, either by:
* correcting the term URI at the EFO end
* replacing obsoleted/duplicated terms in GWAS Catalog with correct EFO terms and re-annotating studies/associations
* requesting term imports from other ontologies or new terms to be created in EFO

**Comment by eks-ebi** [comment]
This ticket can be closed because any outstanding issues are tracked elsewhere:

1. Remaining terms for import /creation tracked in EFO ticket: https://github.com/EBISPOT/efo/issues/1465

2. Created new separate ticket to investigate 1 remaining missing term with no obvious cause: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/647
