### ISSUE TITLE
Missing associations from Regeneron Exome Analyses

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/goci#652]
Hello,

I have noticed differences in the ExWAS results from the Regeneron study ([PMID:34662886](www.ncbi.nlm.nih.gov/pubmed/34662886)) reported in their supplementary data and the associations made available through the GWAS Catalog.

To be more specific, I see no overlap between the accessions reported in the publication and the significant associations reported by the GWAS Catalog.
A major cause is that no results from the burden analyses are processed by the GWAS Catalog. However, in the missing accessions we can find single point associations:
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/b0ca4503-4a46-4757-967f-85e5c448d3b4)

**Data:**
- Significant associations extracted from Supp Data 2 and 3 (downloadable [here](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-04103-z/MediaObjects/41586_2021_4103_MOESM5_ESM.xlsx))
- Latest associations file from GWAS Catalog (downloadable [here](https://www.ebi.ac.uk/gwas/api/search/downloads/alternative)) filtered to include only records from PMID:34662886.

**Steps to reproduce:**
- I've merged together Supplementary Data 2 (associations from European ancestries) with Supplementary Data 3 (non European) to get a dataset of all the significant associations.
- This table is then joined with Supplementary Data 4 (summary stats with the GWAS Catalog accessions) to extract the GCST IDs.
- The resulting table is then joined with the GWAS Catalog associations on the GCST accession to extract those rows which are not contained in the GWAS Catalogue associations.

This protocol can be seen here, where you can see that the entirety of the Regeneron associations is not found in GWAs Catalog: https://github.com/ireneisdoomed/random_notebooks/blob/main/exome_data/regeneron/exploration.ipynb

It would be great if you can clarify this.

**Comment by earlEBI** [comment]
The study accessions in the above table image are for the gene-burden studies. 

The associations for eg. 6mm weak meridian left (5097) can be found in the single variant study accession: [GCST90079274](https://www.ebi.ac.uk/gwas/studies/GCST90079274) 

single variant study accessions are in SD4, filtering study tag column to end in '_SV'
![Screenshot 2022-03-22 at 09 31 23](https://user-images.githubusercontent.com/61545198/159449920-c00e137d-a81b-4ed9-9c0d-798679e1512a.png)

To note: 
- Associations for ancestries other than European have not been extracted as summary statistics submitted were for EA only, and they did not report significant differences between ancestries and I don't think non-EA analyses were genome-wide.
- Replication was taken into account (also reported in SD2). So some associations may not be included due to significance > 1e-5 in DiscovEHR cohort. 
- SD2 was also filtered so that only the top association per 100kb was extracted. 

Please let me know if I can help clear anything else up
