### ISSUE TITLE
The port for the ingest URL is not being updated when the ingest service is deployed

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/goci#678]
We need a solution for when the ingest service is deployed and the port is dynamically reassigned. This affects the services that need to connect to the ingest service via the port (they need their properties updated in order to work). Curation and Deposition sync are affected by this.

**Comment by sajo-ebi** [comment]
Blocked by a dependency on Web Prod team to give us process to implement traffic manager changes , Once they provide the details will restart the changes

**Comment by sprintell** [comment]
Firewall changes have been done, @sajo-ebi  needs to deploy the changes in config and ...

**Comment by sajo-ebi** [comment]
Config changes to make context root changes deployed to Prod & Curation App has been restarted with Load balancer configuration, the submission page is now working with Load balancer url

**Comment by sajo-ebi** [comment]
Reopening the issue as we are facing issues with Depo Sync for Unpublished studies because the submissions APi is not paginated & the response is timing out from EBI proxy as it exceeds 2 mins, need to fix the Submissions API in Ingest & also make changes in Depo sync in order to handle paginates studies
