### ISSUE TITLE
Amending corresponding authors details for submission GCP000318 (user request)

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#690]
The user Hongbo Liu has emailed us to ask for a change with the corresponding author for submission GCP000318 - see landing page: https://www.ebi.ac.uk/gwas/studies/GCST90100220.

Current corresponding author name: Hongbo Liu
New corresponding author name:  Katalin Susztak

The user is also asking for a change in the reported trait, but this amendment can be done with depo-curation app.

These changes will appear in the UI only after the next data release

**Comment by sajo-ebi** [comment]
@ljwh2 the corresponding author information in Search UI is same as first author so to make the change will have to edit first author inform , kindly confirm if that will be fine

**Comment by sprintell** [comment]
@ljwh2  from our conversatiom on this, it seems we wil be more consistent and clearer to the users if we remove the corresponding Author Field in the public facing catalog

**Comment by ljwh2** [comment]
@sprintell I don't totally understand the issue here. Is it not possible for a submitter to enter a first author? Then what is being displayed as first author in the search UI?

**Comment by eks-ebi** [comment]
@ljwh2 to fill you in from last week's meeting, the current problem is that in the Search UI, in the field labelled Corresponding Author, we are not actually displaying the Corresponding Author entered by the submitter when they create a body of work. At the moment we are mistakenly displaying the First Author in that field. That's why, even though the corresponding author for this body of work has been updated to "Katalin Susztak" in the deposition interface, it is still appearing as "Hongbo Liu" in the Search UI.

Last week we decided that the quickest solution would be to remove the Corresponding Author field from the Search UI to avoid displaying erroneous information. The actual Corresponding Author will still be available to curators as contact info. And maybe later we can add the field back in the Search UI and make sure it contains the right data.

**Comment by ljwh2** [comment]
thanks @eks-ebi 
Agree to remove the corresponding author field as a quick fix, but we should prioritise displaying it properly, it's the kind of thing that's important to users, especially for the pre-published data when there isn't so much to tie a submission to the team that generated it. @sprintell @sajo-ebi

**Comment by eks-ebi** [comment]
@eks-ebi inform this user once find has been removed

**Comment by ljwh2** [comment]
Development story created #743
