### ISSUE TITLE
Expanding the usefulness of the error messages provided by the depo-curation app when curators upload study/trait files

### ISSUE THREAD

**Issue by buniello** [EBISPOT/goci#702]
Currently, the depo-curation app only provides a general "unexpected error occurred" message when the trait/study upload fails for any given reason. 
The curators would really benefit from more informative error messages for the different use cases. Below a list of possible reasons for an upload to fail (from real examples):

1. the file has not been saved in tsv extension
2. one or more traits are missing from the database
3. there is a syntax error in the list e.g. extra space or typo
4. file headers not correct - please check the format

5. Curators may add here more examples

**Comment by ljwh2** [comment]
Errors expected to appear in the download file are:
1. Trait not present in DB
2. Study Tag & GCST don’t match
3. GCST not present in DB

**Comment by ala-ebi** [comment]
fixed an error where having an expired session keeps giving 'Unexpected error'. now displays an alert redirects to login page

**Comment by ljwh2** [comment]
@eks-ebi to review

**Comment by eks-ebi** [comment]
Discussed with @ljwh2 today: suggest that errors related to the file as a whole be reported as on-screen error messages in the UI:
1. File does not have .tsv extension
2. File does not have expected headers
3. File does not have the expected number of rows/columns (e.g. not "square", space used instead of tab etc.)
4. ...

If there is one or more errors at the study level (assigned trait does not match database etc.) this should also be indicated briefly in the on-screen error message, but the curator will have to download the error report to see the full details.
e.g. Trait assigning failed for one or more studies - please see error report

Study level errors should then be displayed in the report, for each study:
1. Trait not found in database
2. ...

**Comment by sajo-ebi** [comment]
The code changes have been implemented & are currently being reviewed

**Comment by sajo-ebi** [comment]
Changes have been deployed in Sandbox
