### ISSUE TITLE
Bulk creation of reported traits

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/goci#87]
See https://docs.google.com/document/d/12E_LSalP3tiM4ZPJpA2StknLqbxKOPwcsSJN4teH5X0/edit?ts=5edf5c51#heading=h.lyoak3qqn6us
for spec.
Branch for code: https://github.com/EBISPOT/goci/tree/add_disease_traits

**Comment by tudorgroza** [comment]
**Acceptance criteria:**
1. Curator logs into the Curation App
2. Curator imports submitted publication using the current process 
3. Curator is presented with the option to view a list of studies within the publication with their reported traits (as submitted via the deposition app)
4. On viewing the list, for each study, the following features are presented
 * study tag 
 * submitted reported trait 
 * list of possible matches (eg in a dropdown) of reported traits that already exist in the Catalog, with the closest match first. Those with an exact match to existing reported traits are highlighted. 
 * any background trait 
 * any EFOs submitted
5. With respect to reported traits, Curator is presented with the option to 
 * change individual matches,
 * accept suggested matches, or* add the originally submitted reported trait as a new reported trait
6. Curator is presented with an option to perform either of the second two options in an efficient manner, either by accepting all matches or by adding a new trait to all studies or a subset of studies indicated by tickboxes. 
7. Curator is required to confirm acceptance of the chosen reported traits
8. On actioning the confirmation, the application saves the chosen reported traits to the database, overwriting the originally submitted reported traits.
7. Curator has the option to navigate away from this page to the existing Reported traits page in order to manually search the reported traits, prior to confirming.

**Comment by twhetzel** [comment]
@ljwh2 what page were you expecting to view the list of possible matching reported traits? What are the curator steps after a submission is imported from the Deposition app to the Curation app?

**Comment by ljwh2** [comment]
@twhetzel The best place for the list would be in the Publication view (ie this one: https://www.ebi.ac.uk/gwas/curation/publication/32605384). There's quite a lot going on on that page already, so could be a second tab.

**Comment by eks-ebi** [comment]
Tested after Yomi's recent development work.

Overall impression:
- nice clear look
- easy to find all the features
- buttons/icons are intuitive

Specific features:

1. Single Page Create

- works well

- message is clear: “Success: Data was saved”
2. Single Page validation to avoid duplicate
- If I try to re-enter a trait that already exists (e.g. “Shingles”) I get an error, which is good, but the message is not very informative: “Error: Something went wrong.”
3. Search
- generally works well
- table seems to only start searching once ≥4 characters have been entered - is this intentional?
- happy to see that the search is not case-sensitive
4. Single Page Update
- it wasn’t immediately obvious to me that I could click on the trait name to update it, although it didn’t take too long to guess
- the update panel works well
- the successful update message is very clear (“Disease Trait was updated”)
5. Paginated search result / Adjust size option / count report
- easy to adjust size and reloads quickly
- count report is accurate and updates correctly when I change the number of rows displayed
- navigating between pages does some weird things:
a) clicking on the “1” button goes to page 1, but clicking on the “2” button also goes to page 1, and clicking on the “3” button goes to page 2, and so on…
b) clicking on the “Last” button goes to the 2nd last page, not the last page.
c) the “First” button is disabled while on the first page but the “Last” button is not disabled while on the last page - I would expect the same behaviour for both buttons. Prob caused by the previous issue.
6.	Single Page delete
- delete action works well
- message was not what I would expect: “SyntaxError: JSON.parse: unexpected character at line 1 column”
7.	Single Page Bulk Upload
- Download Disease Trait Template File button is easy to find
- Text: “Ensure you upload CSV File of the required type only” - should it be CSV, TSV or either?
- messages all make sense
- Traits all added successfully
- Tried re-uploading the same template file. I got an error, which seemed to prevent me from uploading duplicate traits. This is good. But the message was not clear: “SyntaxError: JSON.parse: unexpected character at line 1 column”
8.	Reported Trait Similarity Analysis
- Text: “Upload csv or tsv File of the required type only …” - should it be CSV, TSV or either? This should be consistent with the message for the Bulk Upload above.
- upload worked well
- messages were all clear
- download of analysis results worked well. However the downloaded results file has the .csv extension but seems to actually be formatted as a tab-separated file. That meant that when I opened it in excel, it tried to separate by comma instead of tab and gave me some weird column splits. I would recommend keeping as a .tsv throughout (to match the other files used on this page).
- the actual analysis results seem to make sense and look like they will very useful
9.	Statistical Visualization
- the Trait Chart is clear, easy to follow, looks really nice - I think this will give us a good overview of the traits in the Catalog
- I wasn't really sure what the Network Visualisation is supposed to show. What relationship is expressed by the edges between the nodes?
10.	Better User Experience Layout Design
- overall the layout and design are really nice and I think the user experience is smooth and intuitive
- I think we should take this opportunity to move away from using “Disease Traits” - this is a term that is only used in the curation interface and doesn’t match how this entity is named in the search UI, deposition interface etc. It is also a bit inaccurate, because not all of the traits are necessarily diseases or disease-related. Recommend instead using “Reported Trait” throughout this page.
- From a UX perspective, how does the element in the top panel relate to the search/list of traits in the bottom panel. Does the list need to be present alongside each top panel element? e.g. if I open the Network Visualisation, this doesn’t seem to have anything to do with the search/list - as a user I might expect that searching for something in the list will somehow change what is displayed in the visualisation, but this isn’t the case.
11.	API Driven
- I didn’t test this.
12.	Delete prompt (coming up later)
