### ISSUE TITLE
Gather requirements to have GWAS data searchable in the EBI Covid portal

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/goci#92]
Request from Helen:

Hi,

to have the Covid19 data in the Catalog available in the Covid19 portal then we need to be indexed in EBI search. This is a simple JSON export. Could you please add this to the future feature requests?

thanks

Helen

**Comment by JalMacArthur** [comment]
See below additional information on what is required from Youngmi (ympark@ebi.ac.uk) in Rodrigo’s Web Prod team:

Hi Guy and Jackie,

First, thank you for calling me expert!

This is general information about EBI Search:
https://www.ebi.ac.uk/seqdb/confluence/display/EXT/EBI+Search+Engine

There is a section about indexing data:
https://www.ebi.ac.uk/seqdb/confluence/display/EXT/EBI+Search+Engine#EBISearchEngine-dataFormatsDataformats

Please feel free to find me if you need any information or have questions.

Best regards,
Youngmi

**Comment by ljwh2** [comment]
Additional info from Thomas Keane's team:

Hi Dylan+Mallory,

Now that EGA and GWAS have got their first COVID datasets, Guy Cochrane has asked Helen and I if there could be a tag added to EGA/GWAS COVID studies so that they can be indexed by the COVID data portal. He said they are adding a specific tab on the website for human studies and are keen to get the indexing automated. It would be best if EGA and GWAS catalog would use the same tag, hence cc'ing Laura. Fpr ENA studies, they are using pathogen taxonomy but clearly that would not work for EGA/GWAS catalog.

-- 
Rgds,
Thomas
---
Dear Thomas, Dylan, Mallory,

In the GWAS Catalog we annotating studies with the EFO term for COVID-19 (imported from MONDO https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100096). Is this the sort of tag you are referring to? 
Some of the COVID data we have coming in is not associated with a journal publication, which currently means it does not get an ontology term in the GWAS Catalog (something we may change in the future). 

Best wishes, Laura
--------
Hi Laura,

We can tag using that, but I would suggest we use the textual synonyms as listed in EFA as well as many searches will just use text.

Thanks,

Dylan

**Comment by twhetzel** [comment]
To start the process to have GWAS Catalog data indexed in the EBI Search the form here needs to be filled out:
https://docs.google.com/forms/d/e/1FAIpQLSfRr_5RUsp9qJ6qy5wqgZwOc6BjfNUCyiyOaq10z5YgSkw_dg/formResponse

Here are the general information values:
- Contact email: gwas-info
- Name: GWAS Catalog helpdesk if it will accept that or otherwise PL
- Description: The GWAS catalog is a database of human SNP-trait associations derived from genome-wide association studies. 
- Domain:  “Genomes and metagenomes”

**Comment by twhetzel** [comment]
Initial form contents submitted. Will need to provide more details to EBI Search team on what values to index and what values to display.
