### ISSUE TITLE
Testing new sumstats format - validation in Dev environ

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#933]
I've had some intermittent issues when uploading submission template in Dev environment, testing new sumstats format. 

1. 30854688
template: [https://app.zenhub.com/files/2995118/115bc6fd-1ef3-4881-8b5d-e6f223cdaccc/download](https://app.zenhub.com/files/2995118/115bc6fd-1ef3-4881-8b5d-e6f223cdaccc/download)
Error: No error. Just continually 'validating' over days. 
note: genotyping technology is wrong in the template but this should return an error explaining as such.

**Comment by earlEBI** [comment]
2. PMID 30610198
63c94aced3c06e0001dc4191
template: [https://app.zenhub.com/files/2995118/f1d009f6-006f-4952-96bf-8fa9bd125463/download](https://app.zenhub.com/files/2995118/f1d009f6-006f-4952-96bf-8fa9bd125463/download)
Error: 
pvalue0_validtest-shouldpasswithtemplate.tsv: There is a problem on our side, please contact gwas-subs@ebi.ac.uk for further advice.

But I've validated the file offline and have also successfully submitted this file through other submissions.

**Comment by sajo-ebi** [comment]
@earlEBI Analysed both the submissions , 

for  Pmid -> '30854688' the sumstats submission was failing due to Pattern mismatch issue with regards to Read me text column , there was a non ascii character & the pattern validation which has been written to handle non ascii characters for Read me column is running in infinite loop , James will look to fix that pattern.

In order to continue your testing can you remove the non ascii value from the Read me text column in the row with GCST 'GCST007737'

for Pmid  '30610198' -> this has to be analysed from sumstats side @jdhayhurst can you please check for callbackId 'WGRtQrgD' what is the error in sumstats service

**Comment by earlEBI** [comment]
@sajo-ebi If you can reset PMID 30854688 / stop the ongoing validation, I'll remove the ascii value and reupload. Or I can just try with a new PMID.

**Comment by ljwh2** [comment]
Is this resolved @earlEBI ?
